### ISSUE TITLE
SC-GCP n2-highmem-32 disk configuration

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-price-calculator#20]
Same issue as https://github.com/scylladb/siren/issues/6343

**Comment by AdarBahar** [comment]
@omrivardi 
line [112](https://github.com/scylladb/scylla-price-calculator/blob/master/lib/src/models/ScyllaCloud.ts)
```
 name: 'n2-highmem-32',
            vcpu: 32,
            memory: 256,
            storage: 7500,
            computePrice: {
                ondemand: 2130.64,
                reserved: 1346.98
```

Update storage to 9000
Update prices: 
- ondemand: 2250.64
- reserved: 1423.48

Is there another place in the calc code to update?

**Comment by AdarBahar** [comment]
@omrivardi please note - I've update the prices in the description.
I suggest you add to the code a note (for me, next time) that the prices per each instance are instance (cloud) prices only, not including the subscription

**Comment by tzach** [comment]
@omrivardi @AdarBahar any update?

**Comment by omrivardi** [comment]
https://github.com/scylladb/scylla-price-calculator/pull/21 will fix it as we move to use the cloud API

**Comment by AdarBahar** [comment]
fixed. This can be closed
![image](https://user-images.githubusercontent.com/62795576/155119783-5b91a5f9-5c1c-4da7-a0e4-ef16380c0f1e.png)
