### ISSUE TITLE
Support GCP instances (for Scylla Cloud)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-price-calculator#9]

**Comment by AdarBahar** [comment]
@nukemberg 
All the details are here: https://docs.google.com/spreadsheets/d/1unKvljBcgk8rx3OKzMIbhHplLYvcLI-rPUCTQGg5eHo/edit?ts=6023c475#gid=69689044 including prices

Regions:
South Carolina (us-east1)
Montreal (northamerica-northeast1)
Sao Paulo (southamerica-east1)
Belgium (europe-west1)
Finland (europe-north1)
London (europe-west2)
Frankfurt(europe-west3)
Netherlands (europe-west4)
Singapore (asia-southeast1)
Sydney (australia-southeast1)
Taiwan (asia-east1)
Hong Kong (asia-east2)
Tokyo (asia-northeast1)

Instances type:
n2-highmem-2
n2-highmem-4
n2-highmem-8
n2-highmem-16
n2-highmem-32
n2-highmem-48
n2-highmem-64
n2-highmem-80

**Comment by tzach** [comment]
@nukemberg can we close this?
